name: the new reality
favicon: null
layout_spectrum: 0.5956513697747141
typography_spectrum: 0.5664772854652256
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5690169599838555
  lightness: 0.5053637863602489
  saturation: 0.7222550532314926
  rhythmicContrast: 0.2030885184649378
purpose: []
